/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { SetStateAction, useEffect, useMemo, useRef, useState } from "react";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { useGrid } from "@/hooks/useGrid";
import { socket } from "../SocketManager";
import { push, ref, set } from "firebase/database";
import { realtimeDb } from "@/firebase/firebase";

const MOVEMENT_SPEED = 4;
interface CharacterProps {
  position?: THREE.Vector3;
  path?: Array<[number, number, number]>;
  id?: string;
  avatarUrl?: string;
}
export function Avatar({
  id,
  avatarUrl = "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb",
  ...props
}: CharacterProps) {
  const [chatMessage, setChatMessage] = useState("");
  const position = useMemo(() => props.position, []);

  const avatar = useRef<THREE.Object3D | null>(null);
  const [path, setPath] = useState<Array<THREE.Vector3>>();
  const grid = useGrid();

  const group = useRef<THREE.Group>(null);
  const { scene } = useGLTF(avatarUrl);
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo<THREE.Object3D>(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials

  const { animations: walkAnimation } = useGLTF("/animations/M_Walk_001.glb");
  const { animations: danceAnimation } = useGLTF("/animations/M_Dances_001.glb");
  const { animations: idleAnimation } = useGLTF("/animations/M_Standing_Idle_001.glb");

  const { actions } = useAnimations(
    [walkAnimation[0], idleAnimation[0], danceAnimation[0]],
    avatar
  );
  const [animation, setAnimation] = useState("M_Standing_Idle_001");
  const [isDancing, setIsDancing] = useState(false);
  const [showChatBubble, setShowChatBubble] = useState(false);
  const postChatMessage = (name: string, chatMessage: string) => {
    const postRef = ref(realtimeDb, "chat");
    const newPostRef = push(postRef);
    set(newPostRef, {
      name: name,
      message: chatMessage,
      timestamp: Date.now(),
    });
  };
  useEffect(() => {
    clone.traverse((child) => {
      if (child instanceof THREE.Mesh && child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
  }, [clone]);

  useEffect(() => {
    const action = actions[animation];
    if (action) {
      action.reset().fadeIn(0.1).play();
      return () => {
        action.fadeOut(0.1);
      };
    }
  }, [animation, avatarUrl]);

  useEffect(() => {
    function onPlayerAnimation(value: {
      id: string | undefined;
      animationName: SetStateAction<string>;
    }) {
      if (value.id === id) {
        setAnimation(value.animationName);
      }
    }
    function onPlayerMove(value: { id: string | undefined; path: [number, number, number][] }) {
      if (value.id === id) {
        const path: THREE.Vector3[] = [];
        value.path.forEach((gridPosition: [number, number, number]) => {
          path.push(grid!.gridToVector3(gridPosition));
        });
        setPath(path);
      }
    }

    let chatMessageBubbleTimeOut: NodeJS.Timeout;
    const TIME_OUT = 5000;
    function onChatMessage(value: {
      id: string | undefined;
      name: string | undefined;
      message: string;
    }) {
      if (value.id === id) {
        setChatMessage(value.name + ": " + value.message);
        clearTimeout(chatMessageBubbleTimeOut);
        postChatMessage(value.name || "", value.message);
        setShowChatBubble(true);
        chatMessageBubbleTimeOut = setTimeout(() => {
          setShowChatBubble(false);
        }, TIME_OUT);
      }
    }
    socket.on("playerAnimation", onPlayerAnimation);
    socket.on("playerMove", onPlayerMove);
    socket.on("playerChatMessage", onChatMessage);
    return () => {
      socket.off("playerAnimation", onPlayerAnimation);
      socket.off("playerMove", onPlayerMove);
      socket.off("playerChatMessage", onChatMessage);
    };
  }, [id]);

  useFrame((_state, delta) => {
    if (!avatar.current || !group.current) return;
    const hips = avatar.current.getObjectByName("Hips");
    hips?.position.set(0, hips.position.y, 0);
    if (path?.length && group.current.position.distanceTo(path[0]) > 0.1) {
      const direction = group.current.position
        .clone()
        .sub(path[0])
        .normalize()
        .multiplyScalar(MOVEMENT_SPEED * delta);
      group.current.position.sub(direction);
      group.current.lookAt(path[0]);
      setAnimation("M_Walk_001");
      setIsDancing(false);
    } else if (path?.length) {
      path.shift();
    } else {
      if (isDancing) {
        setAnimation("M_Dances_001");
      } else {
        setAnimation("M_Standing_Idle_001");
      }
    }
  });

  return (
    <group ref={group} {...props} position={position} dispose={null} name={`character-${id}`}>
      <Html position-y={2}>
        <div className="w-60 max-w-full">
          <p
            className={`absolute max-w-full text-center break-words -translate-y-full p-2 px-4 -translate-x-1/2 rounded-lg bg-white bg-opacity-40 backdrop-blur-sm text-black transition-opacity duration-500 ${
              showChatBubble ? "" : "opacity-0"
            }`}
          >
            {chatMessage}
          </p>
        </div>
      </Html>
      <motion.group
        initial={{
          y: 3,
          rotateY: Math.PI * 4,
          scale: 0,
        }}
        animate={{
          y: 0,
          rotateY: 0,
          scale: 1,
        }}
        transition={{
          delay: 0.8,
          mass: 5,
          stiffness: 200,
          damping: 42,
        }}
      >
        <primitive object={clone} ref={avatar} />
      </motion.group>
    </group>
  );
}

useGLTF.preload(
  localStorage.getItem("avatarURL") ||
    "https://models.readyplayer.me/64f0265b1db75f90dcfd9e2c.glb?meshlod=1&quality=medium"
);
useGLTF.preload("/animations/M_Walk_001.glb");
useGLTF.preload("/animations/M_Standing_Idle_001.glb");
useGLTF.preload("/animations/M_Dances_001.glb");
useGLTF.preload("/animations/M_Standing_Expressions_001.glb");
